-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

        DROP TABLE IF EXISTS "Death";

        CREATE TABLE IF NOT EXISTS "Death"
        (
            death_id integer NOT NULL,
            date date,
            "time" time without time zone,
            location_code integer,
            investigated boolean,
            cause_id character varying(10),
            description character varying(500),
            time_relative_birth integer,
            pregnancy_type integer,
            gestational_age integer,
            birth_type integer,
            deceased_occupation integer,
            deceased_marital_status integer,
            deceased_age double precision,
            deceased_weight double precision,
            deceased_education_level integer,
            deceased_race_color integer,
            deceased_sex integer,
            mother_living_children integer,
            mother_deceased_children integer,
            mother_education_level integer,
            mother_age double precision,
            mother_occupation double precision
        );

        DROP TABLE IF EXISTS "Location";

        CREATE TABLE IF NOT EXISTS "Location"
        (
            "IBGE_city_code" integer NOT NULL,
            city_name character varying(200) NOT NULL,
            "GDP" real,
            "GDP_per_capita" real,
            population_estimate_2009 double precision,
            "IBGE_state_code" integer,
            state_name character varying(200),
            "basic_health_unit_CNES" integer,
            basic_health_unit_name character varying(200)
        );
        END;